### ISSUE TITLE
Create Chess Pieces

### ISSUE THREAD

**Issue by StevenCataluna** [sweng-group-30/Microsoft-Hololens-Chess-Game#1]
# Create functional Chess pieces that can be manipulated with AR.

- [x] Pawn
- [x] Knight
- [x] Bishop
- [x] Rook
- [x] #8
- [x] King

**Comment by rzheng0904** [comment]
i ll take the 👸 queen

**Comment by sulliv-luke** [comment]
I'll do the Knight

**Comment by soodt** [comment]
I'll take the king

**Comment by LKYMichelle** [comment]
I'll do the Pawn
